version: '3.8'

services:
  # Aplicación Go Clean Architecture
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    restart: unless-stopped
    networks:
      - clean-arch-network

  # PostgreSQL (para futura implementación)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cleanarch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clean-arch-network
    restart: unless-stopped

  # Redis (para futura implementación de cache)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - clean-arch-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  clean-arch-network:
    driver: bridge
